package br.com.igreja.enuns;

public enum Funcao {
	NENHUMA,COOPERADOR, DIÁCONO, PRESBÍTERO, EVANGELISTA, PASTOR, LIDER_SENHORAS, SEGUNDA_LIDER_SENHORAS, REGENTE_SENHORAS, SEGUNDA_REGENTE_SENHORAS, 
	LIDER_JOVENS, SEGUNDA_LIDER_JOVENS, REGENTE_JOVENS, SEGUNDA_REGENTE_JOVENS,LIDER_ADOLESCENTES, SEGUNDA_LIDER_ADOLESCENTES, 
	REGENTE_ADOLESCENTES, SEGUNDA_REGENTE_ADOLESCENTES, LIDER_CRIANÇAS, SEGUNDA_LIDER_CRIANÇAS, REGENTE_CRIANÇAS, SEGUNDA_REGENTE_CRIANÇAS,
	PRIMEIRO_SECRETÁRIO_ESCOLA, SEGUNDO_SECRETÁRIO_ESCOLA,PRIMEIRO_SECRETÁRIO_GERAL, SEGUNDO_SECRETÁRIO_GERAL,
	TESOUREIRO_GERAL,SEGUNDO_TESOUREIRO_GERAL,TESOUREIRO_CIRCULO_ORAÇÃO;
}
