package br.com.igreja.enuns;

public enum PermissaoUsuarioEnum {
	ROLE_ADMIN_SEDE,ROLE_MEMBRO_SEDE, ROLE_TESOUREIRO_SEDE, ROLE_SECRETARIO_SEDE, ROLE_ADMIN_CONGREGACAO, ROLE_TESOUREIRO_CONGREGACAO, 
	ROLE_SECRETARIO_CONGREGACAO;
}
